export interface SubTopic {
    title: string;
  }
  
  export interface Module {
    id: number;
    title: string;
    subtitle: string;
    duration?: string;
    subtopics: SubTopic[];
  }
  
  export const modulesData: Module[] = [
    {
      id: 1,
      title: 'Linux | Shell | Bash | Python',
      subtitle: 'Module 1',
      duration: '2 weeks',
      subtopics: [
        { title: 'Overview of Linux' },
        { title: 'Linux Architecture' },
        { title: 'Linux Distributions' },
        { title: 'Basic Linux Commands' },
        { title: 'File Permission Management' },
        { title: 'User Creation' },
        { title: 'Shell Scripts' },
        { title: 'SSH and VI Utility' },
        { title: 'Creation of User' },
        { title: 'Establishing SSH Connection to the Server' },
        { title: 'File creation and Manipulation using the VI editor' },
        { title: 'Managing permissions' },
        { title: 'Basic commands execution' },
        { title: 'Shell Scripting - History and Introduction' },
        { title: 'Types of shells' },
        { title: 'Shebang line in shell' },
        { title: 'Command line arguments' },
        { title: 'Creating first shell script' },
        { title: 'How to run a shell script' },
        { title: 'Variables and Types of Operators' },
        { title: 'If-else in shell script' },
        { title: 'For loop in shell script' },
        { title: 'While loop in shell script' },
        { title: 'Functions in shell script' },
        { title: 'Python - File Handling' },
        { title: 'Reading and writing files (text and binary)' },
        { title: 'File handling modes (r, w, a, r+)' },
        { title: 'Exception Handling' },
        { title: 'Types of exceptions and errors' },
        { title: 'try, except, finally, else blocks' },
        { title: 'Raising and handling exceptions' },
        { title: 'Working with System and OS Modules' },
        { title: 'os (file operations, environment variables, process management)' },
        { title: 'sys (command-line arguments, exit codes)' },
        { title: 'subprocess (executing shell commands from Python)' },
        { title: 'Object-Oriented Programming (OOP) overview' },
        { title: 'Classes and objects' },
        { title: 'Inheritance' },
        { title: 'Polymorphism' },
        { title: 'Encapsulation' },
        { title: 'Abstraction' },
      ],
    },
    {
      id: 2,
      title: 'DevOps Overview',
      subtitle: 'Module 2',
      duration: '1 week',
      subtopics: [
        { title: 'Evolution of Waterfall, Agile, and DevOps' },
        { title: 'What is DevOps' },
        { title: 'Why DevOps' },
        { title: 'Benefits of DevOps' },
        { title: 'DevOps Stages' },
        { title: 'DevOps Lifecycle' },
        { title: 'Various Automation in DevOps' },
        { title: 'Overview of CI/CD' },
      ],
    },
    {
      id: 3,
      title: 'Managing Source Code – Git and GitHub',
      subtitle: 'Module 3',
      duration: '1 week',
      subtopics: [
        { title: 'Central vs Distributed Version Control System' },
        { title: 'Introduction to Git' },
        { title: 'Installation and Setting-up Git' },
        { title: 'Important Git Commands' },
        { title: 'Creating and Managing git Repositories' },
        { title: 'Git File Workflow' },
        { title: 'GIT - IGNORE' },
        { title: 'Installation and Configuration of Git' },
        { title: 'Creating Git Repositories' },
        { title: 'Demonstrating Various Git Repositories' },
        { title: 'Merging Branches and Managing Merge Conflicts' },
        { title: 'Stashing, Reverting, Rebasing and Resetting' },
        { title: 'Collaborating Local and Remote Repositories' },
        { title: 'GIT Misc Commands' },
        { title: 'Reverting and Resetting' },
        { title: 'GIT Branching Strategies' },
        { title: 'Working with GIT Branching' },
        { title: 'Branching, Merging' },
        { title: 'Rebase and Squash' },
        { title: 'GIT Stash' },
        { title: 'Introduction to GitHub' },
        { title: 'Managing Remote Repositories' },
        { title: 'Handling GitHub repositories using Visual Studio Code' },
      ],
    },
    {
      id: 4,
      title: 'Continuous Integration Using Jenkins',
      subtitle: 'Module 4',
      duration: '2 weeks',
      subtopics: [
        { title: 'Overview of Continuous Integration' },
        { title: 'Difference between Continuous vs Traditional Integration' },
        { title: 'Overview of Jenkins' },
        { title: 'Jenkins Master-Slave Architecture' },
        { title: 'Jenkins Installation and Configuration' },
        { title: 'Jenkins Plugins' },
        { title: 'Jenkins Management' },
        { title: 'Jenkins Freestyle and Pipeline Jobs' },
        { title: 'Scripted and Declarative Pipelines' },
        { title: 'Configuring Slave Node to Jenkins' },
        { title: 'Configure Tomcat Server' },
        { title: 'Integrate and Deploy to Tomcat Server using Jenkins' },
        { title: 'Jenkins Build Triggers' },
        { title: 'Enable Email Notifications' },
        { title: 'Installation and Configuration of Jenkins' },
        { title: 'Configuration of Tools' },
        { title: 'Configuration of Plugins' },
        { title: 'Creation of Freestyle Jobs, Scripted and Declarative Pipeline Jobs' },
        { title: 'Demonstrate Pipeline Triggering Using GitHub Webhooks' },
        { title: 'Integration of Code Coverage Tools and Static Code Analysis Tools' },
        { title: 'Triggering Pipelines Using Git Webhooks' },
        { title: 'Creation of CI/CD Pipelines' },
        { title: 'Adding Slave Node to Jenkins' },
      ],
    },
    {
      id: 5,
      title: 'Containerization, Docker, and Docker Hub',
      subtitle: 'Module 5',
      duration: '2 weeks',
      subtopics: [
        { title: 'Introduction to Virtualization and Containerization' },
        { title: 'What is Containerization' },
        { title: 'Docker Architecture' },
        { title: 'Overview of Docker Hub' },
        { title: 'Docker Installation' },
        { title: 'Docker Commands' },
        { title: 'Container Modes' },
        { title: 'Port Binding' },
        { title: 'Docker file' },
        { title: 'Managing Docker Images' },
        { title: 'Running and Managing Containers' },
        { title: 'Docker Volume' },
        { title: 'Docker Compose' },
        { title: 'Overview of Docker Swarm' },
        { title: 'Installation of Docker and Docker Compose on AWS EC2' },
        { title: 'Running Docker Commands' },
        { title: 'Writing Docker Files for various applications' },
        { title: 'Building Docker Images' },
        { title: 'Pushing Images to Docker Hub' },
        { title: 'Running Docker Containers' },
        { title: 'Container Port Binding' },
        { title: 'Running Multiple Containers Using Docker Compose file' },
        { title: 'Initialize a Docker Swarm and Demonstrate Workload Deployments' },
      ],
    },
    {
      id: 6,
      title: 'Container Orchestration Tool - Kubernetes',
      subtitle: 'Module 6',
      duration: '3 weeks',
      subtopics: [
        { title: 'Overview of Container Orchestration' },
        { title: 'Difference between Docker Swarm and Kubernetes Cluster' },
        { title: 'Kubernetes Architecture' },
        { title: 'Installation of Kubernetes - Minikube and EKS' },
        { title: 'Kubernetes Nodes' },
        { title: 'Kubernetes Pods' },
        { title: 'Kubernetes Deployments' },
        { title: 'Rolling updates and Rollbacks' },
        { title: 'Scaling up and Down of the Application' },
        { title: 'Services in Kubernetes' },
        { title: 'Kubernetes Host Path Volume' },
        { title: 'Namespaces' },
        { title: 'Installation and Configuration of Kubernetes Minikube' },
        { title: 'Creation of Pods and Deployments using Ad-Hoc Commands' },
        { title: 'Creation of Pods and Deployments using YAML files' },
        { title: 'Scaling up and Scaling Down of the Application' },
        { title: 'Rolling out Deployments and Rolling Back' },
        { title: 'Creation of Services' },
        { title: 'What is Helm?' },
        { title: 'What are Helm charts?' },
        { title: 'Why do we need Helm?' },
        { title: 'Advantages of Helm charts' },
        { title: 'Helm relation with Kubernetes' },
        { title: 'Helm search' },
        { title: 'How to pull Helm packages' },
        { title: 'Helm Templates' },
        { title: 'ClusterIP in Helm' },
        { title: 'NodePort in Helm' },
        { title: 'Install/Uninstall helm repositories' },
        { title: 'Helm deployments' },
        { title: 'Integration with Prometheus' },
        { title: 'Integration with Grafana' },
      ],
    },
    {
      id: 7,
      title: 'Configuration Automation using Ansible',
      subtitle: 'Module 7',
      duration: '2 weeks',
      subtopics: [
        { title: 'Overview of Configuration Automation' },
        { title: 'Introduction to Ansible' },
        { title: 'Ansible Architecture' },
        { title: 'Components of Ansible' },
        { title: 'Installation and Configuration of Ansible' },
        { title: 'Ansible Ad-Hoc Commands' },
        { title: 'Ansible Playbooks' },
        { title: 'Ansible Variables' },
        { title: 'Ansible Handlers' },
        { title: 'Ansible Role using Ansible Galaxy' },
        { title: 'Installation and Configuration Ansible' },
        { title: 'Running Ansible Ad-Hoc Commands' },
        { title: 'Writing Ansible Playbooks to Configure Servers' },
        { title: 'Creating Ansible Roles' },
      ],
    },
    {
      id: 8,
      title: 'Terraform Overview',
      subtitle: 'Module 8',
      duration: '2 weeks',
      subtopics: [
        { title: 'Introduction to Terraform' },
        { title: 'Terraform vs. Ansible' },
        { title: 'Terraform Architecture' },
        { title: 'Terraform Configuration' },
        { title: 'Terraform Commands' },
        { title: 'Managing Terraform Resources' },
        { title: 'Terraform End to End Project' },
        { title: 'Installation of Terraform on AWS EC2 Instance' },
        { title: 'Writing Terraform Configuration' },
        { title: 'Creation of AWS EC2 instance using Terraform' },
        { title: 'Managing AWS Resources using Terraform' },
        { title: 'End to End Infrastructure Creation Project' },
      ],
    },
    {
      id: 9,
      title: 'Monitoring, Logging, and Observability',
      subtitle: 'Module 9',
      duration: '2 weeks',
      subtopics: [
        { title: 'What is Prometheus?' },
        { title: 'What is Monitoring?' },
        { title: 'What is Alerting?' },
        { title: 'PromQL language in Prometheus' },
        { title: 'Metrics in Prometheus' },
        { title: 'Service Discovery' },
        { title: 'Third Party components' },
        { title: 'Exporters in Prometheus' },
        { title: 'Ports of Prometheus' },
        { title: 'Architecture of Prometheus' },
        { title: 'Alert Manager' },
        { title: 'TSBD in Prometheus' },
        { title: 'Retrieval in Prometheus' },
        { title: 'HTTP Server' },
        { title: 'Jobs in Prometheus' },
        { title: 'Integration with Helm' },
        { title: 'Integration with Grafana' },
        { title: 'Prometheus Dashboard' },
        { title: 'Prometheus Helm charts' },
        { title: 'Integration with Kubernetes' },
        { title: 'What is Grafana?' },
        { title: 'Why do we need Grafana?' },
        { title: 'Advantages of Grafana' },
        { title: 'Grafana Queries' },
        { title: 'Grafana Visualizations' },
        { title: 'Grafana Alerts' },
        { title: 'Grafana Dashboards' },
        { title: 'How to analyze metrics' },
        { title: 'Integration with Prometheus' },
      ],
    },
    {
      id: 10,
      title: 'DevOps with AI',
      subtitle: 'Module 10',
      duration: '1 week',
      subtopics: [
        { title: 'AI-Driven Automation: intelligent testing' },
        { title: 'Pipeline optimization' },
        { title: 'Bug detection' },
        { title: 'Predictive Analytics: forecasting failures' },
        { title: 'Capacity planning' },
        { title: 'Anomaly detection' },
        { title: 'Incident Management: AI-based root cause analysis' },
        { title: 'Reduced MTTR' },
        { title: 'Security with AI (AIOps): automated vulnerability scanning' },
        { title: 'Threat detection' },
        { title: 'AI in Monitoring: anomaly recognition' },
        { title: 'Self-healing alerts' },
        { title: 'Predictive scaling' },
        { title: 'Optimization & Self-Healing: Kubernetes with AI integrations' },
        { title: 'Dynamic resource allocation' },
      ],
    },
  ];