// ─── Syllabus & Sample Q&A Data ─────────────────────────────────────────────
// Sourced from public/deep-research-report.md — AWS official exam guides.

export interface SyllabusDomain {
  name: string;
  percent: number;
  keyTopics: string;
}

export interface SampleQuestion {
  domain: string;
  question: string;
  options: string[];
  multiSelect?: boolean;
  answer: string;
  explanation: string;
}

export interface CertSyllabus {
  code: string;
  title: string;
  level: string;
  domains: SyllabusDomain[];
  sampleQA: SampleQuestion[];
  studyTips: string[];
  resources: string[];
  studyWeeks: string;
}

export const CERT_SYLLABUS: CertSyllabus[] = [
  {
    code: "CLF-C02",
    title: "AWS Certified Cloud Practitioner",
    level: "Foundational",
    domains: [
      { name: "Cloud Concepts", percent: 24, keyTopics: "Benefits of cloud (agility, elasticity), Well-Architected pillars, migration strategies, cloud economics" },
      { name: "Security & Compliance", percent: 30, keyTopics: "AWS Shared Responsibility Model, security in the cloud (IAM, encryption), compliance (AWS Artifact)" },
      { name: "Cloud Technology & Services", percent: 34, keyTopics: "AWS Global Infrastructure (Regions, AZs), compute (EC2, Lambda, ECS/EKS), storage (S3, EBS, EFS), database (RDS, DynamoDB), networking (VPC, Route 53, VPN/Direct Connect), AI/ML, analytics, IoT" },
      { name: "Billing, Pricing & Support", percent: 12, keyTopics: "Compute/storage pricing (On-Demand, Reserved, Spot, Savings Plans), cost tools (Budgets, Cost Explorer), consolidated billing, Support plans" },
    ],
    sampleQA: [
      {
        domain: "Cloud Concepts",
        question: "Which of the following is a benefit of deploying applications in multiple Availability Zones (AZs)?",
        options: ["High availability through redundant deployment across AZs.", "Lower data transfer costs between instances in different AZs.", "The ability to use Spot Instances without interruption.", "Less latency for all users globally."],
        answer: "High availability through redundant deployment across AZs.",
        explanation: "Deploying in multiple AZs increases fault tolerance and availability. Inter-AZ data transfer actually incurs charges, Spot Instances can still be interrupted, and latency depends on region placement.",
      },
      {
        domain: "Security & Compliance",
        question: "Under the AWS Shared Responsibility Model, which security tasks are the customer's responsibility?",
        options: ["Encrypting data at rest on Amazon S3 buckets.", "Ensuring IAM password policy enforcement.", "Maintaining the physical security of AWS data centers.", "Patching the guest operating system on EC2 instances."],
        multiSelect: true,
        answer: "Encrypting data at rest on Amazon S3 buckets; Ensuring IAM password policy enforcement; Patching the guest operating system on EC2 instances.",
        explanation: "AWS is responsible for physical security of data centers. Customers handle OS patching, encryption of their own data, and IAM policies.",
      },
      {
        domain: "Cloud Technology & Services",
        question: "A developer needs to process real-time streaming data for a data analytics application. Which AWS service should they use?",
        options: ["Amazon SQS.", "Amazon Kinesis Data Streams.", "AWS Batch.", "Amazon Athena."],
        answer: "Amazon Kinesis Data Streams.",
        explanation: "Kinesis Data Streams is designed for real-time streaming data processing. SQS is for message queuing, Batch is for batch jobs, and Athena is for querying data stored in S3.",
      },
      {
        domain: "Cloud Technology & Services",
        question: "What is the main purpose of Amazon CloudFront (an edge location)?",
        options: ["Storing large datasets in the cloud.", "Caching static content to reduce latency for global users.", "Providing a static IP address for EC2 instances.", "Managing Domain Name System (DNS) records."],
        answer: "Caching static content to reduce latency for global users.",
        explanation: "CloudFront caches content at edge locations to reduce latency for end users worldwide.",
      },
      {
        domain: "Billing, Pricing & Support",
        question: "Which AWS Support plan provides architectural guidance and recommendations for cost optimization?",
        options: ["Basic.", "Developer.", "Business.", "Enterprise."],
        answer: "Enterprise.",
        explanation: "The Enterprise support plan includes access to technical account managers and Well-Architected reviews, which cover cost optimization guidance.",
      },
      {
        domain: "Billing, Pricing & Support",
        question: "A company expects variable workloads on their EC2 instances. Which purchasing option minimizes cost while allowing flexible compute usage?",
        options: ["On-Demand Instances.", "Reserved Instances.", "Spot Instances.", "Dedicated Hosts."],
        answer: "Spot Instances.",
        explanation: "Spot Instances offer steep discounts for interruptible workloads, giving high elasticity and cost savings for variable workloads.",
      },
    ],
    studyTips: [
      "Don't overthink simple questions; Cloud Practitioner focuses on foundational concepts.",
      "Pay attention to AWS terms (e.g., \"elasticity,\" \"global reach\" are often cited benefits).",
      "For multi-response questions, ensure all correct answers are chosen.",
      "Watch for distractors that sound AWS-y but are incorrect.",
      "Use AWS resources (e.g., FAQs, Knowledge Center) to clarify service details.",
    ],
    resources: [
      "Overview of AWS (AWS whitepaper) — cloud fundamentals",
      "AWS Well-Architected Framework whitepaper",
      "AWS Shared Responsibility Model (Knowledge Center)",
      "AWS Pricing page and AWS Cost Optimization blog",
      "AWS Skill Builder: AWS Cloud Practitioner Essentials",
      "AWS Ramp-Up Guide: Cloud Practitioner",
      "Hands-on labs: AWS Free Tier (EC2, S3, IAM) and Well-Architected Labs",
    ],
    studyWeeks: "2–4",
  },
  {
    code: "AIF-C01",
    title: "AWS Certified AI Practitioner",
    level: "Foundational",
    domains: [
      { name: "Fundamentals of AI/ML", percent: 20, keyTopics: "AI/ML basics (ML, Deep Learning, LLM, NLP), learning types (supervised/unsupervised, reinforcement), AI/ML pipeline steps" },
      { name: "Fundamentals of Generative AI", percent: 24, keyTopics: "GenAI concepts (foundation models, LLMs, multi-modality), Amazon Bedrock, Amazon Q, prompt engineering basics" },
      { name: "Applications of Foundation Models", percent: 28, keyTopics: "Using FMs for vision/chat/text tasks, custom vs pretrained models, AWS GenAI services, use cases (chatbots, summarization)" },
      { name: "Responsible AI Guidelines", percent: 14, keyTopics: "Ethical considerations (bias, fairness), data privacy, model explainability, compliance, AWS guardrail tools" },
      { name: "Security, Compliance & Governance for AI", percent: 14, keyTopics: "Securing AI (access control, data encryption), compliance in AI workflows, KMS, IAM, AWS Artifact" },
    ],
    sampleQA: [
      {
        domain: "Fundamentals of AI/ML",
        question: "Which of the following best describes a generative AI (GenAI) model?",
        options: ["A system that makes decisions based on hard-coded rules.", "A model that can generate new content (text, images) by learning from data.", "A type of supervised learning model that only predicts numerical values.", "A model used exclusively for computer vision tasks."],
        answer: "A model that can generate new content (text, images) by learning from data.",
        explanation: "GenAI models (e.g., LLMs) generate new data based on learned patterns; they generalize from training data and aren't rule-based or limited to numeric output.",
      },
      {
        domain: "Fundamentals of AI/ML",
        question: "Which scenario is NOT a suitable use case for machine learning?",
        options: ["Predicting housing prices from features (area, location).", "Performing straightforward arithmetic calculations.", "Classifying emails into spam or not-spam.", "Identifying anomalies in sensor data streams."],
        answer: "Performing straightforward arithmetic calculations.",
        explanation: "Simple arithmetic is deterministic and doesn't require ML — ML is best for prediction, classification, and pattern recognition tasks.",
      },
      {
        domain: "Fundamentals of Generative AI",
        question: "What is a foundation model (FM) in the context of AWS AI services?",
        options: ["An AWS machine learning model used only for data classification.", "A large pretrained model (often an LLM) offered by AWS or open-source for building AI applications.", "A generative adversarial network (GAN) architecture provided by SageMaker.", "The base infrastructure template for deploying AI servers."],
        answer: "A large pretrained model (often an LLM) offered by AWS or open-source for building AI applications.",
        explanation: "Foundation models are large pretrained models (e.g., Amazon Titan or open LLMs) that can be fine-tuned or used via AWS Bedrock.",
      },
      {
        domain: "Applications of Foundation Models",
        question: "Which AWS service would you use to summarize customer feedback texts using AI?",
        options: ["Amazon Translate.", "Amazon Polly.", "Amazon Kendra.", "Amazon Comprehend or Amazon Bedrock."],
        answer: "Amazon Comprehend or Amazon Bedrock.",
        explanation: "Comprehend (NLP insights) or Bedrock (foundation models) can summarize text. Translate handles language translation, Polly is text-to-speech, and Kendra is search.",
      },
      {
        domain: "Responsible AI Guidelines",
        question: "Which practice helps ensure responsible use of AI/ML in deployments?",
        options: ["Monitoring model outputs for biased or inappropriate content.", "Tuning hyperparameters until accuracy is 100%.", "Providing human oversight or review for critical decisions.", "Avoiding any use of cloud resources for data privacy."],
        multiSelect: true,
        answer: "Monitoring model outputs for biased or inappropriate content; Providing human oversight or review for critical decisions.",
        explanation: "Responsible AI involves detecting bias and including human review or guardrails for high-stakes decisions. Tuning to 100% accuracy risks overfitting, and avoiding cloud resources doesn't address privacy controls.",
      },
      {
        domain: "Security, Compliance & Governance for AI",
        question: "What AWS feature helps protect sensitive data when using SageMaker?",
        options: ["AWS KMS (Key Management Service) for encrypting data at rest and in transit.", "Amazon GuardDuty automatically masks data.", "AWS IAM prevents any data export.", "AWS Snowball for offline encryption."],
        answer: "AWS KMS (Key Management Service) for encrypting data at rest and in transit.",
        explanation: "KMS keys can encrypt S3 data and EBS volumes used by SageMaker. GuardDuty is for threat detection, IAM manages access, and Snowball is for data transfer.",
      },
    ],
    studyTips: [
      "Do not confuse AI/ML concepts with traditional programming; know basic definitions (supervised vs unsupervised).",
      "For GenAI, focus on capabilities of AWS services (Bedrock, Q, SageMaker AI) and terminology like \"foundation model\".",
      "Ethical considerations (bias, fairness) are frequently tested — think of real-world ML use cases.",
      "Use AWS examples (e.g., summarizing text with Comprehend) to ground abstract questions.",
    ],
    resources: [
      "AI & ML Glossary on the AWS site",
      "AWS GenAI Well-Architected Guide (whitepaper)",
      "AWS Blog posts on Amazon Bedrock, Amazon SageMaker AI",
      "AWS Skill Builder: AI Cloud Practitioner and Generative AI learning paths",
      "AWS GenAI Labs (Bedrock labs) for hands-on prompts and foundation models",
      "AWS free-tier practice: SageMaker, Comprehend, Polly, Rekognition",
    ],
    studyWeeks: "3–4",
  },
  {
    code: "MLA-C01",
    title: "AWS Certified Machine Learning Engineer – Associate",
    level: "Associate",
    domains: [
      { name: "Data Preparation for ML", percent: 28, keyTopics: "Data sources and formats, cleaning and transformation, feature engineering, labeling data, AWS data services (S3, Glue, Kinesis)" },
      { name: "ML Model Development", percent: 26, keyTopics: "Selecting algorithms, SageMaker training jobs, hyperparameter tuning, evaluation metrics, SageMaker Clarify for bias detection" },
      { name: "Deployment & Orchestration of ML Workflows", percent: 22, keyTopics: "Deploying models (endpoints, batch transform), CI/CD (CodePipeline, CodeDeploy), IaC (CloudFormation, SageMaker Pipelines)" },
      { name: "ML Solution Monitoring, Maintenance & Security", percent: 24, keyTopics: "Monitoring model performance, retraining triggers, CloudWatch logs, securing ML resources (IAM roles, encryption, VPC endpoints)" },
    ],
    sampleQA: [
      {
        domain: "Data Preparation for ML",
        question: "Which action is a best practice when preparing data for training?",
        options: ["Mixing categorical and numeric values without encoding.", "Filling missing numeric values with feature mean or median.", "Training on raw text without tokenization for NLP tasks.", "Using training data that the model has never seen during hyperparameter tuning."],
        answer: "Filling missing numeric values with feature mean or median.",
        explanation: "Imputing missing values helps model learning. Categorical data should be encoded, raw text needs tokenization, and option D is unrelated to good practice.",
      },
      {
        domain: "ML Model Development",
        question: "A model on SageMaker is underfitting. What might help?",
        options: ["Increase the model complexity (e.g., deeper neural network).", "Add more noise to the training data.", "Train longer or provide more training data.", "Reduce number of training epochs."],
        multiSelect: true,
        answer: "Increase the model complexity (e.g., deeper neural network); Train longer or provide more training data.",
        explanation: "Underfitting means the model is too simple or undertrained. Adding noise or reducing epochs would worsen it further.",
      },
      {
        domain: "ML Model Development",
        question: "What metric would you use to evaluate a classification model with imbalanced classes?",
        options: ["Accuracy.", "Precision/Recall or F1-score.", "Mean Squared Error.", "Sum of Absolute Differences."],
        answer: "Precision/Recall or F1-score.",
        explanation: "Precision/Recall (or F1) handle class imbalance well; accuracy can be misleading on imbalanced data.",
      },
      {
        domain: "Deployment & Orchestration of ML Workflows",
        question: "You want to automate model deployment to production. Which AWS service can orchestrate an ML pipeline (from data preprocessing to endpoint deployment)?",
        options: ["AWS Step Functions.", "AWS CodePipeline.", "Amazon SageMaker Pipelines.", "AWS Elastic Beanstalk."],
        answer: "Amazon SageMaker Pipelines.",
        explanation: "SageMaker Pipelines is purpose-built for ML workflow orchestration. Step Functions coordinates general tasks, CodePipeline is for app CI/CD, and Beanstalk is for web apps.",
      },
      {
        domain: "ML Solution Monitoring, Maintenance & Security",
        question: "A deployed model starts performing worse over time due to concept drift. What is a best practice to handle this?",
        options: ["Retrain the model periodically with new data.", "Disable model endpoint to stop drift.", "Switch to an older model.", "Increase the instance type of the endpoint."],
        answer: "Retrain the model periodically with new data.",
        explanation: "Retraining with fresh data addresses drift directly; disabling the endpoint or switching models doesn't fix the underlying issue.",
      },
      {
        domain: "ML Solution Monitoring, Maintenance & Security",
        question: "Which AWS feature helps secure sensitive data in S3 used for training?",
        options: ["S3 buckets cannot be encrypted by design.", "Use S3 Server-Side Encryption with KMS-managed keys.", "Use HTTP instead of HTTPS to access S3.", "Public access for audit logging."],
        answer: "Use S3 Server-Side Encryption with KMS-managed keys.",
        explanation: "S3 SSE-KMS ensures data at rest is encrypted. Always use HTTPS and avoid public bucket exposure.",
      },
    ],
    studyTips: [
      "Data Prep: ensure training data is well-processed (handle missing values, normalize, encode labels) — feeding raw data is a common trap.",
      "Model Tuning: watch for overfitting vs underfitting; monitor validation metrics, not just training metrics.",
      "Deployment: understand real-time vs batch options and test endpoints with sample data.",
      "Cost Management: turn off notebook/endpoint instances when not in use.",
      "Read questions carefully — \"continuous deployment\" points to SageMaker Pipelines or CodePipeline, not a generic answer.",
    ],
    resources: [
      "Amazon SageMaker Developer Guide (training, tuning, pipelines)",
      "AWS Solutions Implementations for MLOps",
      "AWS labs: SageMaker training, SageMaker Clarify, CodePipeline CI/CD",
      "Machine Learning Pipeline on AWS (Skill Builder)",
      "Architecting with AI/ML – Specialty and MLOps Engineer Learning Plan (Skill Builder)",
      "Kaggle / AWS Open Datasets for pipeline practice",
    ],
    studyWeeks: "4–6",
  },
  {
    code: "SAA-C03",
    title: "AWS Certified Solutions Architect – Associate",
    level: "Associate",
    domains: [
      { name: "Design Secure Architectures", percent: 30, keyTopics: "IAM best practices, encryption at rest/in transit, network security (security groups, NACLs), web app security (WAF, Shield)" },
      { name: "Design Resilient Architectures", percent: 26, keyTopics: "High availability (Multi-AZ, Multi-Region), fault tolerance, disaster recovery (backup, pilot light)" },
      { name: "Design High-Performing Architectures", percent: 24, keyTopics: "Compute scaling (Auto Scaling, Load Balancers), database solutions (RDS vs DynamoDB), caching (ElastiCache), performance optimization" },
      { name: "Design Cost-Optimized Architectures", percent: 20, keyTopics: "Right-sizing, reserved vs spot instances, storage classes (S3 tiers), cost tools (Trusted Advisor, Cost Explorer)" },
    ],
    sampleQA: [
      {
        domain: "Design Secure Architectures",
        question: "You are designing a VPC with public and private subnets. Which approach ensures the highest security for database instances?",
        options: ["Place DB instances in a public subnet with a public IP.", "Place DB instances in a private subnet with no internet gateway and restrict by security groups.", "Use AWS WAF on the DB instance.", "Encrypt RDS with a public KMS key."],
        answer: "Place DB instances in a private subnet with no internet gateway and restrict by security groups.",
        explanation: "Putting databases in private subnets with no direct internet access, accessible only via security group rules from application servers, is the most secure design.",
      },
      {
        domain: "Design Resilient Architectures",
        question: "What mechanism provides near zero data loss for a cross-region failover of a database?",
        options: ["Multi-AZ synchronous replication in RDS.", "Multi-Region asynchronous read-replica promotion.", "Backups restored on new region.", "Route 53 health check swap."],
        answer: "Multi-Region asynchronous read-replica promotion.",
        explanation: "A read replica in another region (e.g., Aurora Global Database) can be promoted; Multi-AZ only covers within one region, backups are too slow, and a Route 53 swap is just a DNS change.",
      },
      {
        domain: "Design High-Performing Architectures",
        question: "Your web application experiences unpredictable traffic spikes. Which design improves performance under high load?",
        options: ["Use Auto Scaling groups for EC2 behind an Application Load Balancer.", "Switch RDS from Multi-AZ to Single-AZ.", "Use Amazon ElastiCache (Redis/Memcached) for session caching.", "Increase EBS volume size for database storage."],
        multiSelect: true,
        answer: "Use Auto Scaling groups for EC2 behind an Application Load Balancer; Use Amazon ElastiCache (Redis/Memcached) for session caching.",
        explanation: "Auto Scaling handles spikes and caching offloads DB reads. Single-AZ reduces HA, and increasing EBS size may help IOPS but doesn't scale reads.",
      },
      {
        domain: "Design Cost-Optimized Architectures",
        question: "How can you reduce costs for EBS-backed instances that run continuously?",
        options: ["Replace EBS with instance store volumes.", "Use Reserved Instances or Savings Plans.", "Use On-Demand Instances only during peak hours.", "Migrate the workload to Fargate."],
        answer: "Use Reserved Instances or Savings Plans.",
        explanation: "Committing to RI/Savings Plans lowers hourly cost. Instance store is ephemeral, full-time on-demand is costlier, and Fargate is serverless but only applies to containers.",
      },
      {
        domain: "Design Secure Architectures",
        question: "To protect data in S3, which actions are recommended?",
        options: ["Enable S3 Versioning and MFA Delete on buckets.", "Make buckets public with IP restrictions.", "Enable default encryption (SSE-S3 or SSE-KMS).", "Use IAM user for cross-account access without roles."],
        multiSelect: true,
        answer: "Enable S3 Versioning and MFA Delete on buckets; Enable default encryption (SSE-S3 or SSE-KMS).",
        explanation: "Both versioning/MFA delete and default encryption enhance security. Avoid public buckets, and use IAM Roles rather than sharing user credentials for cross-account access.",
      },
      {
        domain: "Design High-Performing Architectures",
        question: "Which AWS service accelerates static content delivery globally?",
        options: ["Amazon CloudFront.", "AWS Global Accelerator.", "AWS Direct Connect.", "Amazon ElastiCache."],
        answer: "Amazon CloudFront.",
        explanation: "CloudFront (CDN) caches static assets at edge locations worldwide. Global Accelerator speeds up static IP access, Direct Connect is a private link, and ElastiCache is an in-region cache.",
      },
    ],
    studyTips: [
      "Pay careful attention to multi-tier architecture design (correct subnet placement with NAT, IGWs).",
      "Always verify whether failover across AZs vs Regions is needed — know RA vs HA differences.",
      "For cost questions, compare instance pricing models and storage tiers.",
      "Use the AWS console to explore sample architecture blueprints for guidance.",
    ],
    resources: [
      "AWS Well-Architected Framework (core principles)",
      "AWS Security Best Practices whitepaper (IAM, encryption)",
      "AWS Storage/Database FAQs (RDS vs DynamoDB)",
      "Architecting on AWS (official course)",
      "AWS Well-Architected Labs for hands-on design patterns",
      "Third-party practice exams for Solutions Architect",
    ],
    studyWeeks: "6–8",
  },
  {
    code: "DVA-C02",
    title: "AWS Certified Developer – Associate",
    level: "Associate",
    domains: [
      { name: "Development with AWS Services", percent: 32, keyTopics: "App design patterns (stateless, microservices), AWS SDK/CLI, REST APIs (API Gateway/Lambda), messaging (SQS, SNS), data stores (DynamoDB, S3)" },
      { name: "Security", percent: 26, keyTopics: "IAM roles/permissions for applications, securing access keys, Secrets Manager, Cognito, encryption in code" },
      { name: "Deployment", percent: 24, keyTopics: "CI/CD pipelines (CodeCommit, CodeBuild, CodePipeline), packaging (SAM, CloudFormation), environment variables, rollbacks" },
      { name: "Troubleshooting & Optimization", percent: 18, keyTopics: "Monitoring (CloudWatch Logs/Metrics), debugging (X-Ray), performance tuning (lazy loading, caching), cost-efficient code" },
    ],
    sampleQA: [
      {
        domain: "Development with AWS Services",
        question: "You need to decouple an application's components. Which AWS service should you use for asynchronous messaging?",
        options: ["Amazon S3.", "Amazon SNS.", "Amazon SQS.", "AWS Lambda."],
        answer: "Amazon SQS.",
        explanation: "SQS (Simple Queue Service) is a queue for decoupling and async message handling. SNS is pub/sub, S3 is storage, and Lambda is compute.",
      },
      {
        domain: "Development with AWS Services",
        question: "Which statement about AWS SDKs is true?",
        options: ["AWS SDKs only support Python and Java.", "SDKs allow programmatic access to AWS services (APIs) from code.", "SDK calls do not require AWS credentials.", "SDKs automatically retry failed requests without configuration."],
        answer: "SDKs allow programmatic access to AWS services (APIs) from code.",
        explanation: "SDKs provide API libraries for coding in various languages, require credentials, and let you configure retries.",
      },
      {
        domain: "Security",
        question: "How should an application store database credentials securely?",
        options: ["In plaintext in source code.", "In AWS Secrets Manager and reference them at runtime.", "In user's local machine.", "Hard-coded in Lambda environment variables."],
        answer: "In AWS Secrets Manager and reference them at runtime.",
        explanation: "Use AWS Secrets Manager or Parameter Store for credentials — plaintext, local storage, or hard-coded secrets are all insecure.",
      },
      {
        domain: "Deployment",
        question: "You want to automate deployments when code is pushed. Which AWS tool helps set up a continuous delivery pipeline?",
        options: ["AWS CodeStar.", "AWS Elastic Beanstalk.", "AWS CodePipeline.", "AWS CloudHSM."],
        answer: "AWS CodePipeline.",
        explanation: "CodePipeline is the service purpose-built for continuous delivery pipelines. CodeStar is a starter project, Beanstalk is a managed platform, and CloudHSM is hardware security.",
      },
      {
        domain: "Troubleshooting & Optimization",
        question: "An API is slow. After logging, you find a Lambda function is timing out. What can you do?",
        options: ["Increase the Lambda function's timeout setting.", "Add more memory/CPU to the Lambda function.", "Reduce the payload size of API calls.", "Convert the Lambda to run as an On-Demand EC2 instance."],
        multiSelect: true,
        answer: "Increase the Lambda function's timeout setting; Add more memory/CPU to the Lambda function.",
        explanation: "Increasing timeout and/or allocating more memory (which gives more CPU) directly addresses timeouts. Reducing payload may help but isn't guaranteed, and switching to EC2 is unnecessary for a serverless API.",
      },
      {
        domain: "Troubleshooting & Optimization",
        question: "Which AWS service can help debug issues in a distributed application (microservices)?",
        options: ["AWS X-Ray.", "Amazon SQS.", "AWS CodeCommit.", "AWS Trusted Advisor."],
        answer: "AWS X-Ray.",
        explanation: "AWS X-Ray provides tracing and debugging information for distributed apps. SQS is messaging, CodeCommit is a code repo, and Trusted Advisor is for cost/security recommendations.",
      },
    ],
    studyTips: [
      "Remember the difference between SQS (queue) and SNS (topic/pub-sub) to avoid confusion.",
      "Do not hard-code credentials; use IAM roles for Lambdas and Secrets Manager for secrets.",
      "For environment-specific settings, use environment variables or Parameter Store — not source code.",
      "Watch for answers that break least-privilege (e.g., \"use root account\" or \"disable encryption\") — these are traps.",
    ],
    resources: [
      "Amazon SQS Developer Guide, Amazon SNS Developer Guide, AWS SDK Reference",
      "AWS Lambda Developer Guide (deployment and resource best practices)",
      "Developing on AWS (official course)",
      "Tutorials: building serverless APIs with API Gateway & Lambda",
      "Hands-on: CodePipeline from CodeCommit to a Lambda deployment",
      "CloudWatch Logs and X-Ray troubleshooting exercises",
    ],
    studyWeeks: "4–6",
  },
  {
    code: "SOA-C02",
    title: "AWS Certified SysOps Administrator – Associate",
    level: "Associate",
    domains: [
      { name: "Monitoring, Logging & Remediation", percent: 20, keyTopics: "CloudWatch (alarms, dashboards, logs), CloudTrail, AWS Config, automated remediation (EventBridge, Systems Manager)" },
      { name: "Reliability & Business Continuity", percent: 16, keyTopics: "Backup strategies, snapshots, multi-AZ deployments, DR planning (pilot light, warm standby)" },
      { name: "Deployment, Provisioning & Automation", percent: 18, keyTopics: "IaC (CloudFormation, OpsWorks), configuration management (Ansible, Systems Manager), Auto Scaling groups" },
      { name: "Security & Compliance", percent: 16, keyTopics: "IAM user/group policies, key rotation, OS patching, SSM for compliance, patch management" },
      { name: "Networking & Content Delivery", percent: 18, keyTopics: "VPC setup (subnets, routing, IGW, NAT), Direct Connect, VPN, CloudFront, Route 53" },
      { name: "Cost & Performance Optimization", percent: 12, keyTopics: "Cost monitoring (Billing console, Budgets), Trusted Advisor checks, right-sizing, spot instances, DynamoDB modes" },
    ],
    sampleQA: [
      {
        domain: "Monitoring, Logging & Remediation",
        question: "Which CloudWatch feature allows you to execute an action when a metric crosses a threshold?",
        options: ["CloudWatch Logs.", "CloudWatch Events.", "CloudWatch Alarms.", "CloudWatch Dashboards."],
        answer: "CloudWatch Alarms.",
        explanation: "CloudWatch Alarms watch metrics and trigger notifications or actions. CloudWatch Events (EventBridge) routes events, Logs handles logs, and Dashboards is UI only.",
      },
      {
        domain: "Reliability & Business Continuity",
        question: "Your primary database is in one AZ. To enable quick recovery from AZ failure, you should:",
        options: ["Take regular snapshots and restore in same AZ.", "Enable Multi-AZ on the DB instance.", "Copy backup to on-prem.", "Use DynamoDB with global tables."],
        answer: "Enable Multi-AZ on the DB instance.",
        explanation: "Multi-AZ provides automated failover to another AZ. Snapshots restore manually, on-prem is slower, and DynamoDB is a different service entirely.",
      },
      {
        domain: "Deployment, Provisioning & Automation",
        question: "Which service helps automate patch management for EC2 instances?",
        options: ["AWS Lambda.", "AWS Elastic Beanstalk.", "AWS Systems Manager (SSM) Patch Manager.", "AWS CodeDeploy."],
        answer: "AWS Systems Manager (SSM) Patch Manager.",
        explanation: "Systems Manager Patch Manager can schedule and automate patching. Lambda is general compute, Beanstalk is an app platform, and CodeDeploy deploys code.",
      },
      {
        domain: "Security & Compliance",
        question: "How should an admin enforce MFA for all IAM users?",
        options: ["Attach an IAM policy requiring MFA to all users.", "Configure MFA device for root only (covers all).", "Use AWS Organizations service control policy.", "Enable MFA delete on S3 (triggers MFA for login)."],
        answer: "Attach an IAM policy requiring MFA to all users.",
        explanation: "Apply an IAM policy that denies actions unless MFA is used. Root MFA doesn't enforce for IAM users; SCPs can help but need OU setup; MFA delete is only for S3 object deletion.",
      },
      {
        domain: "Networking & Content Delivery",
        question: "Which VPC component allows instances in a private subnet to initiate outbound internet traffic?",
        options: ["Internet Gateway.", "NAT Gateway or NAT Instance.", "Virtual Private Gateway.", "Egress-Only Internet Gateway."],
        answer: "NAT Gateway or NAT Instance.",
        explanation: "A NAT Gateway in a public subnet lets private instances reach the internet while blocking inbound. IGWs attach only to public subnets, VP Gateways are for VPN, and egress-only is for IPv6.",
      },
      {
        domain: "Cost & Performance Optimization",
        question: "How can you reduce costs of underutilized EC2 instances?",
        options: ["Delete the instances immediately.", "Resize instances to a smaller type or use Savings Plans.", "Change AMIs to reduce cost.", "Stop instances instead of terminating them."],
        answer: "Resize instances to a smaller type or use Savings Plans.",
        explanation: "Right-sizing and Savings Plans directly cut costs. Deleting is too severe, stopping just pauses billing temporarily, and changing AMIs alone doesn't reduce compute cost.",
      },
    ],
    studyTips: [
      "Always associate CloudWatch alarms with SNS or automated actions to remediate, not just alert.",
      "For DR, know RTO/RPO differences and AWS backup services (AWS Backup, snapshots).",
      "Confirm route tables and NACLs when troubleshooting connectivity — a common miss.",
      "Use existing AWS Config managed rules for compliance checks (e.g., ensure all volumes are encrypted).",
    ],
    resources: [
      "Amazon CloudWatch User Guide (Alarms, Metrics)",
      "AWS Systems Manager Administration Guide (Patch Manager, Run Command)",
      "VPC Documentation (NAT/IGW) and Route 53 Guide",
      "Trusted Advisor checks (Cost/Performance)",
      "Systems Operations on AWS (official course)",
      "AWS Cost Explorer and Billing console tutorials",
    ],
    studyWeeks: "6–8",
  },
  {
    code: "DEA-C01",
    title: "AWS Certified Data Engineer – Associate",
    level: "Associate",
    domains: [
      { name: "Data Ingestion & Transformation", percent: 34, keyTopics: "ETL/ELT pipelines (Glue, Data Pipeline, Kinesis), real-time ingestion (Kinesis, Kafka), batch processing (Glue jobs, EMR), Glue DataBrew" },
      { name: "Data Store Management", percent: 26, keyTopics: "Data lake architecture (S3, Lake Formation), data modeling (Redshift, RDS, DynamoDB), schema/catalog (Glue Catalog, Athena)" },
      { name: "Data Operations & Support", percent: 22, keyTopics: "Orchestration (Glue workflows, Step Functions), monitoring (CloudWatch for pipelines), debugging ETL jobs, data quality checks" },
      { name: "Data Security & Governance", percent: 18, keyTopics: "Access control (Lake Formation permissions, IAM), encryption, data masking, compliance (CloudTrail, AWS Config)" },
    ],
    sampleQA: [
      {
        domain: "Data Ingestion & Transformation",
        question: "Which AWS service would you use to ingest streaming data from IoT devices?",
        options: ["Amazon S3.", "AWS Glue.", "Amazon Kinesis Data Streams.", "AWS Database Migration Service."],
        answer: "Amazon Kinesis Data Streams.",
        explanation: "Kinesis Data Streams is designed for high-throughput streaming ingestion. S3 is storage, Glue is ETL, and DMS is for migrating databases.",
      },
      {
        domain: "Data Store Management",
        question: "When storing data in Amazon S3 for analytics, how can you organize the data for efficient querying?",
        options: ["Store all data in a single flat bucket.", "Organize data by prefixes/partitions (e.g., year/month) and use AWS Glue Data Catalog.", "Use multiple S3 accounts to separate data.", "Use the AWS console search to find data quickly."],
        answer: "Organize data by prefixes/partitions (e.g., year/month) and use AWS Glue Data Catalog.",
        explanation: "Partitioning with a Glue Catalog improves query performance in Athena/Redshift Spectrum. A single flat bucket slows queries, multiple accounts complicate access, and console search is manual.",
      },
      {
        domain: "Data Operations & Support",
        question: "To automate a data pipeline that runs daily and ingests new files from S3, which AWS service can orchestrate this workflow?",
        options: ["AWS Lambda.", "AWS Step Functions or AWS Glue Workflows.", "Amazon SQS.", "AWS CodePipeline."],
        answer: "AWS Step Functions or AWS Glue Workflows.",
        explanation: "Step Functions (or Glue Workflows) can coordinate multi-step data pipelines on a schedule. Lambda alone isn't enough for complex pipelines, SQS just queues, and CodePipeline is for code.",
      },
      {
        domain: "Data Security & Governance",
        question: "Which feature ensures that sensitive data in S3 is encrypted by default?",
        options: ["S3 Bucket Policies.", "Default Encryption on S3 (SSE-S3 or SSE-KMS).", "Encrypting data at application layer only.", "IAM policies requiring encryption in requests."],
        answer: "Default Encryption on S3 (SSE-S3 or SSE-KMS).",
        explanation: "S3 default encryption ensures all new objects are encrypted with KMS or AES256. Bucket policies can enforce it but default encryption is simpler; app-layer encryption alone isn't systemically enforced.",
      },
      {
        domain: "Data Security & Governance",
        question: "What is AWS Lake Formation used for?",
        options: ["Querying data without servers.", "Building data catalogs and setting granular data permissions on S3 data lakes.", "Visualizing data dashboards.", "Hosting machine learning models."],
        answer: "Building data catalogs and setting granular data permissions on S3 data lakes.",
        explanation: "Lake Formation simplifies creation of data lakes by centralizing access control and cataloging S3 data. Athena/Redshift do querying, QuickSight does dashboards, and SageMaker hosts ML.",
      },
      {
        domain: "Data Ingestion & Transformation",
        question: "A data ingestion pipeline is failing due to IAM permission errors. Which AWS feature can help you debug which permission is missing?",
        options: ["AWS Security Hub.", "AWS Config.", "AWS CloudTrail logs to review denied events.", "Amazon QuickSight to visualize permissions."],
        answer: "AWS CloudTrail logs to review denied events.",
        explanation: "CloudTrail logs show failed API calls with \"Access Denied\" errors, pinpointing missing IAM permissions. Config tracks resource state, Security Hub aggregates findings, and QuickSight is for analytics.",
      },
    ],
    studyTips: [
      "On partitioning S3 data, ensure query engines (Athena/Redshift Spectrum) point to the partitioned keys for performance.",
      "Always validate IAM roles/policies for Glue and Lambda when pipelines fail — CloudTrail is your friend for debugging access issues.",
      "Use the Glue Data Catalog (Schema Registry) to track table schemas.",
      "Remember data service limits (Kinesis throughput, Glue job size) and how to monitor/scale them.",
    ],
    resources: [
      "AWS Glue Developer Guide (ETL operations, catalog)",
      "Amazon Kinesis Developer Guide (streams and analytics)",
      "Amazon S3 Documentation (data lake best practices, encryption)",
      "Data Analytics Fundamentals (free digital training)",
      "Hands-on labs: end-to-end pipeline with Kinesis → Lambda → S3",
      "Data Lake Formation tutorials and AWS Big Data blog posts",
    ],
    studyWeeks: "4–6",
  },
  {
    code: "DOP-C02",
    title: "AWS Certified DevOps Engineer – Professional",
    level: "Professional",
    domains: [
      { name: "SDLC Automation", percent: 22, keyTopics: "CI/CD pipelines (CodeCommit/Build/Deploy), AWS Code* services, automated testing and deployments, infrastructure testing" },
      { name: "Configuration Management & IaC", percent: 17, keyTopics: "Infrastructure as Code (CloudFormation, Terraform), config tools (Chef, Puppet, Ansible on AWS), bootstrapping instances" },
      { name: "Resilient Cloud Solutions", percent: 15, keyTopics: "High availability and fault tolerance (auto-scaling, multi-region services), scaling CI/CD infrastructure" },
      { name: "Monitoring & Logging", percent: 15, keyTopics: "CloudWatch, X-Ray, centralized logging, metric collection, Dashboards, event notification (SNS, EventBridge)" },
      { name: "Incident & Event Response", percent: 14, keyTopics: "Disaster recovery planning (RTO/RPO), automated recovery (Lambda & CloudWatch Events), runbooks, DDoS mitigation" },
      { name: "Security & Compliance", percent: 17, keyTopics: "IAM/IAM Identity Center, secrets management, vulnerability scanning (Inspector, GuardDuty), audit logging" },
    ],
    sampleQA: [
      {
        domain: "SDLC Automation",
        question: "You need an automated pipeline that triggers when a developer pushes code. Which sequence of AWS services is a typical CI/CD setup?",
        options: ["CodeCommit → CodeBuild → CodeDeploy → CodePipeline.", "CodeCommit → CodePipeline → CodeBuild → CodeDeploy.", "S3 → Lambda → CloudWatch → SNS.", "CloudFormation → OpsWorks → Elastic Beanstalk."],
        answer: "CodeCommit → CodePipeline → CodeBuild → CodeDeploy.",
        explanation: "CodePipeline orchestrates stages, CodeBuild compiles/tests, and CodeDeploy pushes to servers — option A places CodePipeline last, which is incorrect ordering.",
      },
      {
        domain: "Configuration Management & IaC",
        question: "How can you define AWS infrastructure in code to ensure consistent deployments?",
        options: ["Use AWS CLI manually on each environment.", "Create AWS CloudFormation templates.", "Write bash scripts to configure each server.", "Launch instances directly from the console."],
        answer: "Create AWS CloudFormation templates.",
        explanation: "CloudFormation (or Terraform) enables declarative IaC for repeatable stacks. Manual CLI or console use is error-prone, and bash scripts are less manageable at scale.",
      },
      {
        domain: "Monitoring & Logging",
        question: "Which service provides an aggregated view of application logs for multi-instance systems?",
        options: ["Amazon CloudWatch Logs (with a log group collecting logs from all instances).", "AWS X-Ray Collector.", "AWS CloudTrail (application logs).", "Amazon SQS Queue."],
        answer: "Amazon CloudWatch Logs (with a log group collecting logs from all instances).",
        explanation: "CloudWatch Logs can ingest and aggregate logs from multiple instances into central log groups. X-Ray traces calls, CloudTrail logs AWS API calls, and SQS is messaging.",
      },
      {
        domain: "Incident & Event Response",
        question: "During a critical application failure, what is the first step in incident response?",
        options: ["Automatically re-deploy the last successful build.", "Notify stakeholders via SNS/SMS.", "Contain and isolate the incident (e.g., scale down impacted services) and collect diagnostics (logs).", "Wait for engineers to come online."],
        answer: "Contain and isolate the incident (e.g., scale down impacted services) and collect diagnostics (logs).",
        explanation: "First contain the issue and gather evidence (logs, metrics) before further action. Immediate redeploy or notification-first approaches can cause noise, and waiting is not proactive.",
      },
      {
        domain: "Security & Compliance",
        question: "Which AWS service can identify security misconfigurations and vulnerabilities on EC2 instances?",
        options: ["Amazon Inspector.", "AWS Config.", "Amazon Macie.", "AWS Shield."],
        answer: "Amazon Inspector.",
        explanation: "Amazon Inspector scans EC2 for vulnerabilities and deviations from security best practices. Config checks resource compliance, Macie detects data loss on S3, and Shield handles DDoS.",
      },
      {
        domain: "SDLC Automation",
        question: "For blue/green deployments with minimal downtime, which AWS tool is appropriate?",
        options: ["AWS Elastic Beanstalk blue/green.", "AWS Lambda only.", "AWS Trusted Advisor.", "AWS CloudTrail."],
        answer: "AWS Elastic Beanstalk blue/green.",
        explanation: "Elastic Beanstalk supports blue/green environment swapping. Lambda isn't designed for app blue/green switches, and Trusted Advisor/CloudTrail are unrelated to deployment strategy.",
      },
    ],
    studyTips: [
      "Emphasize automation: manual steps risk inconsistency — always use IaC.",
      "Test pipelines thoroughly (dry runs, rollback plans).",
      "Monitoring should include application-level metrics (X-Ray or custom CloudWatch metrics), not just AWS metrics.",
      "For high availability, know RDS Multi-AZ vs global clusters for multi-region designs.",
      "Keep security in mind at each step (least-privilege IAM roles for CodeBuild/Deploy).",
    ],
    resources: [
      "AWS DevOps Introduction and AWS Containers/CI-CD blogs",
      "AWS Elastic Beanstalk, Amazon Inspector, AWS Code* suite documentation",
      "DevOps Engineering on AWS (official course)",
      "Hands-on: CodePipeline that builds and deploys via CloudFormation provisioning",
      "AWS Well-Architected DevOps pillar whitepaper",
    ],
    studyWeeks: "8–10",
  },
  {
    code: "SAP-C02",
    title: "AWS Certified Solutions Architect – Professional",
    level: "Professional",
    domains: [
      { name: "Organizational Complexity", percent: 26, keyTopics: "Multiple accounts/regions (Organizations, SCPs), hybrid connectivity (Direct Connect, Transit Gateway), centralized logging/monitoring" },
      { name: "Design for New Solutions", percent: 29, keyTopics: "Global load balancing, event-driven microservices (SNS, SQS, EventBridge), storage optimizations, multi-account strategies" },
      { name: "Continuous Improvement (Existing Solutions)", percent: 25, keyTopics: "Refactoring legacy systems (lift-and-shift vs re-architect), scaling on demand, blue/green & canary deployments" },
      { name: "Migration & Modernization", percent: 20, keyTopics: "Migration Hub, DMS, containers (ECS/EKS), serverless, data migration (Snowball, Database Migration Service)" },
    ],
    sampleQA: [
      {
        domain: "Organizational Complexity",
        question: "An enterprise has multiple AWS accounts. How can you centrally enforce tagging policies?",
        options: ["Use AWS Config Rules for tag compliance across accounts (via AWS Organizations integration).", "Manually audit each account.", "Enable CloudTrail in one account only.", "Use local IAM policies."],
        answer: "Use AWS Config Rules for tag compliance across accounts (via AWS Organizations integration).",
        explanation: "AWS Config with a Config Rule can check tags across member accounts, and Organizations can aggregate config. Manual audits are error-prone, and CloudTrail/local IAM policies don't enforce tags.",
      },
      {
        domain: "Design for New Solutions",
        question: "You need a global failover for a web application with minimal downtime. Which solution?",
        options: ["Active-Active deployment with Route 53 latency-based routing across regions.", "Single region with CloudFront.", "Active-Passive using S3 static website.", "DynamoDB global tables only."],
        answer: "Active-Active deployment with Route 53 latency-based routing across regions.",
        explanation: "Deploying the app in two regions behind ALBs with Route 53 latency routing provides true global failover. CloudFront helps performance but not backend DR; a passive S3 site or global tables alone aren't sufficient.",
      },
      {
        domain: "Continuous Improvement (Existing Solutions)",
        question: "Which deployment strategy minimizes downtime and enables quick rollback?",
        options: ["Rolling update (one instance at a time).", "Blue/Green deployment (switch routers to new environment).", "In-place update without rollback mechanism.", "Manual server reboot."],
        answer: "Blue/Green deployment (switch routers to new environment).",
        explanation: "Blue/Green allows switching traffic with DNS or a load balancer (e.g., weighted Route 53) and immediate rollback if needed.",
      },
      {
        domain: "Migration & Modernization",
        question: "Which AWS service is appropriate for migrating a large Hadoop data warehouse to S3 for analytics?",
        options: ["AWS Snowball (for bulk data transfer).", "AWS Direct Connect (for ongoing).", "S3 Batch Operations.", "AWS CodeCommit."],
        answer: "AWS Snowball (for bulk data transfer).",
        explanation: "Snowball (or multiple Snowballs) is used for migrating large on-prem datasets to S3. Direct Connect is a link, Batch Operations is for S3 tasks, and CodeCommit is irrelevant here.",
      },
      {
        domain: "Design for New Solutions",
        question: "A company wants to securely connect on-premises data center to AWS. Which AWS feature should they use?",
        options: ["Amazon VPC Peering.", "AWS Direct Connect and VPN as fallback.", "AWS IAM Identity Center.", "Amazon CloudFront."],
        answer: "AWS Direct Connect and VPN as fallback.",
        explanation: "Direct Connect provides a high-bandwidth private link, with VPN as backup. VPC peering is AWS-to-AWS only, IAM Identity Center is SSO, and CloudFront is a CDN.",
      },
      {
        domain: "Continuous Improvement (Existing Solutions)",
        question: "When refactoring a legacy 3-tier app for cloud, what is a benefit of using microservices?",
        options: ["All components must be rewritten in the same language.", "You can scale parts independently and deploy updates without affecting the whole app.", "It increases latency and coupling.", "It removes the need for CI/CD."],
        answer: "You can scale parts independently and deploy updates without affecting the whole app.",
        explanation: "Microservices allow independent scaling and deployment of each service — polyglot implementations are allowed, and CI/CD is still needed.",
      },
    ],
    studyTips: [
      "Understand when to lift-and-shift vs re-architect (e.g., migrating databases vs re-platforming to DynamoDB or RDS).",
      "Use Organizations and SCPs to govern large multi-account environments.",
      "Know global AWS services (Route 53, CloudFront, IAM, WAF) vs regional ones.",
      "Pay attention to data transfer costs in multi-region designs.",
    ],
    resources: [
      "AWS Well-Architected Security Pillar (multi-account strategies)",
      "AWS Best Practices for Multi-Region (blog/whitepaper)",
      "Advanced Architecting on AWS (official course)",
      "Labs: Route 53 global failover, Transit Gateway multi-VPC connectivity",
      "AWS Migration Hub for tracking migrations",
    ],
    studyWeeks: "8–10",
  },
  {
    code: "MLS-C01",
    title: "AWS Certified Machine Learning – Specialty",
    level: "Specialty",
    domains: [
      { name: "Data Engineering", percent: 20, keyTopics: "Building data repositories (S3, Kinesis), data preprocessing (Glue, EMR), big data frameworks (Spark on EMR)" },
      { name: "Exploratory Data Analysis", percent: 24, keyTopics: "Data cleaning (missing values), visualization (QuickSight, Matplotlib), feature analysis (correlation, statistics)" },
      { name: "Modeling", percent: 36, keyTopics: "Supervised vs unsupervised, algorithm selection, training vs inference, hyperparameter tuning, evaluation (confusion matrix, ROC/AUC)" },
      { name: "ML Implementation & Operations", percent: 20, keyTopics: "Deploying models (SageMaker endpoints), pipeline automation, monitoring model drift, scaling (GPU vs CPU, multi-model endpoints)" },
    ],
    sampleQA: [
      {
        domain: "Modeling",
        question: "Which algorithm type is best for predicting a numeric value?",
        options: ["Linear regression or tree-based regression.", "K-means clustering.", "Logistic regression.", "Apriori association rules."],
        answer: "Linear regression or tree-based regression.",
        explanation: "Regression algorithms (linear, decision-tree regression) output continuous values. K-means is clustering, logistic regression is classification, and Apriori is for association rules.",
      },
      {
        domain: "Data Engineering",
        question: "What is an advantage of using Amazon S3 over HDFS on EMR for data storage?",
        options: ["S3 provides infinite throughput.", "S3 durability and separation from compute (EMR can scale up/down).", "S3 has built-in SQL query engine.", "HDFS is not supported on AWS."],
        answer: "S3 durability and separation from compute (EMR can scale up/down).",
        explanation: "S3 decouples storage from compute, so an EMR cluster can be terminated without data loss. S3 throughput is large but not infinite, Athena provides SQL on S3, and HDFS is available on EMR.",
      },
      {
        domain: "Exploratory Data Analysis",
        question: "You find missing values in your dataset. Which approach is generally recommended for numerical features?",
        options: ["Replace with mean or median.", "Delete all rows with missing values.", "Replace with zero always.", "Ignore; most algorithms handle nulls natively."],
        answer: "Replace with mean or median.",
        explanation: "Imputing with mean/median preserves dataset size and distribution. Dropping rows loses information, zero can bias results, and few ML algorithms auto-handle nulls.",
      },
      {
        domain: "Modeling",
        question: "Which technique can help prevent overfitting in a neural network model?",
        options: ["Dropout regularization during training.", "Increase the number of layers.", "L2 (ridge) regularization.", "Use more training epochs without early stopping."],
        multiSelect: true,
        answer: "Dropout regularization during training; L2 (ridge) regularization.",
        explanation: "Both methods reduce overfitting; adding layers or training longer without controls can worsen overfitting.",
      },
      {
        domain: "ML Implementation & Operations",
        question: "To deploy a trained model with autoscaling in AWS, which is a valid solution?",
        options: ["SageMaker Real-Time Endpoint with Auto Scaling group of instances behind it.", "Deploy to Lambda with SQS trigger (for batch only).", "SageMaker Multi-Model Endpoint with automatic scaling by SageMaker.", "Use AWS Batch for inference jobs."],
        answer: "SageMaker Multi-Model Endpoint with automatic scaling by SageMaker.",
        explanation: "SageMaker multi-model endpoints can auto-scale with concurrent invocations natively. Lambda is for serverless functions, and Batch is for batch jobs, not real-time inference.",
      },
      {
        domain: "ML Implementation & Operations",
        question: "After deploying an ML model, you notice performance degradation. Which is a sign of data drift?",
        options: ["Changing training hyperparameters.", "A significant drop in model accuracy on new data vs validation.", "Using a larger instance for hosting.", "Receiving more API requests."],
        answer: "A significant drop in model accuracy on new data vs validation.",
        explanation: "If model predictions degrade on fresh data (lower accuracy or unexpected errors), data drift or concept drift may be occurring.",
      },
    ],
    studyTips: [
      "Master data preprocessing (roughly 80% of ML work) — know how to use AWS Glue and Pandas for cleaning.",
      "Distinguish model evaluation metrics (F1 vs accuracy) based on problem context.",
      "When constructing pipelines, separate data sampling for training vs evaluation to avoid leakage.",
      "Monitor cost of training — use spot instances for SageMaker training jobs when feasible.",
    ],
    resources: [
      "Amazon S3 vs HDFS guidance (AWS Big Data blog)",
      "Introduction to Statistical Learning (external context reading)",
      "AWS Builder Labs: Exploratory Data Analysis",
      "Machine Learning on AWS (official classroom/online)",
      "Hands-on: train a model in SageMaker, deploy endpoint, test with new data",
      "Kaggle competitions for model building and analysis practice",
    ],
    studyWeeks: "6–8",
  },
  {
    code: "ANS-C01",
    title: "AWS Certified Advanced Networking – Specialty",
    level: "Specialty",
    domains: [
      { name: "Network Design", percent: 30, keyTopics: "Designing VPCs at scale, transit networks, multi-region connectivity, hybrid architectures (Direct Connect, VPN), IP address planning" },
      { name: "Network Implementation", percent: 26, keyTopics: "VPC implementation (Subnets, Route Tables, IGW, NAT), Transit Gateway, VPC peering, Cloud WAN, Direct Connect setups" },
      { name: "Network Management & Operations", percent: 20, keyTopics: "Monitoring (CloudWatch, VPC Flow Logs), troubleshooting (Reachability Analyzer), network automation (CloudFormation)" },
      { name: "Network Security, Compliance & Governance", percent: 24, keyTopics: "Security groups, NACLs, Firewall Manager, encryption (VPN, Direct Connect), compliance frameworks, WAF & Shield" },
    ],
    sampleQA: [
      {
        domain: "Network Design",
        question: "What is a key benefit of using AWS Transit Gateway in a large organization?",
        options: ["It eliminates the need for any VPC.", "It acts as a central hub to connect multiple VPCs and on-premises networks, simplifying management.", "It provides DDoS protection.", "It automatically encrypts all traffic between regions."],
        answer: "It acts as a central hub to connect multiple VPCs and on-premises networks, simplifying management.",
        explanation: "Transit Gateway connects VPCs/VPNs in a hub-and-spoke model for scalable network architecture. It doesn't replace VPCs, nor is it a security/DDoS service.",
      },
      {
        domain: "Network Implementation",
        question: "Which component allows a private subnet to initiate outbound traffic to the internet?",
        options: ["VPC Peering.", "Elastic IP.", "NAT Gateway or NAT Instance.", "Internet Gateway."],
        answer: "NAT Gateway or NAT Instance.",
        explanation: "A NAT Gateway in a public subnet enables private instances to access the internet; an IGW alone does not allow private subnets outbound access without NAT.",
      },
      {
        domain: "Network Management & Operations",
        question: "How can you capture all traffic flow in a VPC for auditing?",
        options: ["Enable VPC Flow Logs (send to CloudWatch or S3).", "Install a packet sniffer on every EC2.", "Use AWS CloudTrail.", "Use VPC Endpoint logs."],
        answer: "Enable VPC Flow Logs (send to CloudWatch or S3).",
        explanation: "VPC Flow Logs capture IP traffic data in/from network interfaces. CloudTrail logs API calls (not network flow), and packet sniffing on each EC2 is impractical at scale.",
      },
      {
        domain: "Network Security, Compliance & Governance",
        question: "A security requirement mandates SSL/TLS encryption for all web traffic into AWS. Which solution enforces this?",
        options: ["Use an Application Load Balancer with HTTPS listener and SSL cert.", "Create a VPC with an IPsec VPN.", "Launch EC2s in a single subnet.", "Use HTTP to reduce latency."],
        answer: "Use an Application Load Balancer with HTTPS listener and SSL cert.",
        explanation: "An ALB with HTTPS ensures inbound web traffic is encrypted. VPN is for site-to-site (not public web traffic), a single subnet doesn't enforce encryption, and HTTP violates the requirement.",
      },
      {
        domain: "Network Design",
        question: "What IP address range is recommended for VPC CIDR to avoid overlap with on-premises (e.g., 10.0.0.0/16 on-prem)?",
        options: ["10.0.0.0/24 (overlaps).", "192.168.0.0/16 (private, non-overlapping with example).", "172.32.0.0/16 (not private).", "8.8.8.0/24 (public)."],
        answer: "192.168.0.0/16 (private, non-overlapping with example).",
        explanation: "192.168.x.x is private and avoids overlap with an on-prem 10.x.x.x network. 10.0.0.0/24 overlaps, 172.32.0.0 is public, and 8.8.8.0 is Google's public DNS range.",
      },
      {
        domain: "Network Security, Compliance & Governance",
        question: "Which service helps protect web applications from common exploits and bots?",
        options: ["AWS WAF (Web Application Firewall).", "Amazon Cognito.", "AWS CloudHSM.", "AWS Config."],
        answer: "AWS WAF (Web Application Firewall).",
        explanation: "AWS WAF filters HTTP traffic to protect against injection attacks and bots. Cognito is for auth, CloudHSM is key storage, and Config is for compliance.",
      },
    ],
    studyTips: [
      "Remember that security groups are stateful while NACLs are stateless; use both appropriately.",
      "Don't ignore region/peer limits (e.g., max peering connections) — use Transit Gateway for complex topologies.",
      "For multi-region VPCs, use AWS Cloud WAN or multiple Transit Gateways with inter-region peering.",
      "Test your IP schema carefully to avoid collisions, especially in hybrid setups.",
    ],
    resources: [
      "Transit Gateway Developer Guide",
      "Amazon VPC Guide (NAT, subnets, VPC peering)",
      "AWS WAF & Shield Architecture",
      "VPC Flow Logs and Reachability Analyzer docs",
      "Advanced Networking Specialty training courses",
      "AWS Network Automation with CloudFormation templates",
    ],
    studyWeeks: "8–10",
  },
  {
    code: "SCS-C02",
    title: "AWS Certified Security – Specialty",
    level: "Specialty",
    domains: [
      { name: "Threat Detection & Incident Response", percent: 14, keyTopics: "Incident response plans, AWS Security Finding Format (ASFF), GuardDuty alerts, security orchestration (Lambda automated response)" },
      { name: "Security Logging & Monitoring", percent: 18, keyTopics: "CloudTrail logs, AWS Config for compliance, GuardDuty, Security Hub, CloudWatch metrics, log analysis (Logs Insights)" },
      { name: "Infrastructure Security", percent: 20, keyTopics: "Network protection (security groups, NACLs, Firewall Manager), host protection (Inspector), container security (ECR scanning), Shield, WAF" },
      { name: "Identity & Access Management", percent: 16, keyTopics: "IAM best practices (least privilege, MFA, roles vs users), SSO (Identity Center), cross-account access, temporary credentials (STS)" },
      { name: "Data Protection", percent: 18, keyTopics: "Encryption (KMS, CloudHSM, S3 encryption), key management, data classification, tokenization, TLS, VPC endpoints" },
      { name: "Governance & Compliance", percent: 14, keyTopics: "AWS compliance programs, AWS Artifact, policy management (IAM policies, SCPs), CIS benchmarks, audit prep" },
    ],
    sampleQA: [
      {
        domain: "Threat Detection & Incident Response",
        question: "What is the recommended first step in developing an incident response plan?",
        options: ["Compile a list of all IAM users.", "Identify and classify assets/data, define roles/responsibilities.", "Purchase insurance for data breaches.", "Turn off all EC2 instances."],
        answer: "Identify and classify assets/data, define roles/responsibilities.",
        explanation: "First identify critical assets/data and assign incident response roles per AWS best practices. An IAM user list alone is insufficient, insurance is a last resort, and turning off all resources can harm business continuity.",
      },
      {
        domain: "Security Logging & Monitoring",
        question: "Which AWS service provides continuous monitoring and automated threat detection?",
        options: ["AWS Trusted Advisor.", "AWS GuardDuty.", "AWS Config.", "AWS CloudFormation."],
        answer: "AWS GuardDuty.",
        explanation: "GuardDuty monitors VPC flow logs, DNS logs, and CloudTrail for threats like malware and reconnaissance. Trusted Advisor performs static checks, Config tracks compliance state, and CloudFormation is for provisioning.",
      },
      {
        domain: "Infrastructure Security",
        question: "To secure traffic to a public web application, which combination is best?",
        options: ["Security Group allowing all inbound traffic.", "Application Load Balancer with AWS WAF and Shield Advanced.", "Direct Connect with open access.", "Disable encryption to reduce overhead."],
        answer: "Application Load Balancer with AWS WAF and Shield Advanced.",
        explanation: "An ALB over HTTPS with WAF filtering and Shield Advanced for DDoS protection is best practice for public web apps. Opening the SG widely is insecure, Direct Connect doesn't protect against this, and disabling encryption is a security violation.",
      },
      {
        domain: "Identity & Access Management",
        question: "A developer left their IAM access key on a public GitHub repo. What should you do immediately?",
        options: ["Do nothing; public keys are not real.", "Rotate/revoke the key (delete it) and audit usage in CloudTrail.", "Delete the GitHub account.", "Restrict access to S3 only."],
        answer: "Rotate/revoke the key (delete it) and audit usage in CloudTrail.",
        explanation: "Immediately revoke the compromised key and check CloudTrail for any unauthorized use. Deleting the GitHub account is irrelevant to AWS, and restricting S3 alone doesn't secure other services.",
      },
      {
        domain: "Data Protection",
        question: "Which AWS service can help manage encryption keys across accounts?",
        options: ["AWS Key Management Service (KMS) with multi-account key policies.", "AWS Config.", "Amazon Macie.", "AWS X-Ray."],
        answer: "AWS Key Management Service (KMS) with multi-account key policies.",
        explanation: "KMS can create customer master keys and share or create grants across AWS accounts. Config handles config rules, Macie classifies data, and X-Ray is for tracing.",
      },
      {
        domain: "Governance & Compliance",
        question: "Which document provides evidence of AWS compliance controls for your auditors?",
        options: ["AWS Well-Architected Review.", "AWS Artifact (Service Organization Controls report).", "AWS Compliance Whitepaper only.", "Amazon Cognito logs."],
        answer: "AWS Artifact (Service Organization Controls report).",
        explanation: "AWS Artifact provides SOC, ISO, and PCI reports that auditors require. Well-Architected is guidance only, the whitepaper is general public info, and Cognito logs are usage logs.",
      },
    ],
    studyTips: [
      "Follow the principle of least privilege — do not grant overly broad IAM roles/policies.",
      "Always rotate keys and certificates regularly; AWS Config can enforce this (e.g., no root access keys).",
      "Understand the AWS Shared Responsibility Model: AWS secures the cloud, you secure what's in it.",
      "For compliance questions, reference AWS compliance programs (HIPAA, PCI DSS, etc.) as pre-modeled solutions.",
      "Don't forget data-in-transit encryption (TLS, VPC endpoints for S3) as much as data at rest.",
    ],
    resources: [
      "AWS Security Best Practices whitepaper",
      "Incident Response whitepaper",
      "AWS Key Management Service Developer Guide",
      "Amazon GuardDuty & AWS WAF documentation",
      "Security Engineering on AWS (official course)",
      "CIS AWS Foundations Benchmark and OWASP Top 10 (for WAF rule context)",
    ],
    studyWeeks: "8–10",
  },
];

export function getCertSyllabus(code: string): CertSyllabus | undefined {
  return CERT_SYLLABUS.find((c) => c.code === code);
}
